package com.controler;

public enum ControlTransInd {
    SYSTEM_NULL, SYSTEM_SHUT, SYSTEM_HOME, SHOPPING_HOME, SHOPPING_MARKET,
    SHOPPING_CART, PASSWORD_SETTING, MANAGE_HOME, PASSWORD_MANAGE, GOODS_MANAGE, CUSTOM_MANAGE;
}
